package com.example.backend.eduSphere.dto.request;

import lombok.Data;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

/**
 * DTO for receiving data from the frontend when creating or updating an assignment.
 * This represents the data from the 'Add/Edit Assignment' form.
 */
@Data
public class AssignmentRequestDto {

    // Note: We don't include the 'id' here because it will be generated by the database
    // for new assignments.

    private String title;
    private String description;
    private String course;
    private String type;
    private LocalDate dueDate;
    private LocalTime dueTime;
    private int progress;
    private String status;
    private String priority;
    private String instructorId; // We'll receive the ID of the instructor
    private String difficulty;
    private String semester;
    private List<String> badges;

}